# Generated by Django 4.2.7 on 2023-11-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project1_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='GROUP',
            field=models.CharField(choices=[('Chest', 'Chest'), ('Arms', 'Arms'), ('Legs', 'Legs'), ('Back', 'Back'), ('Shoulders', 'Shoulders')], default=str, max_length=200),
            preserve_default=False,
        ),
    ]
